spring:
  application:
    name: bank-architecture
  datasource:
    url: jdbc:mariadb://localhost:3306/bank
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
#        hbm2ddl:
#          foreign_keys: false
#          auto: create